services:
  gitlab-runner:
    image: gitlab/gitlab-runner:${GITLAB_RUNNER_VERSION}
    container_name: gitlab-runner
    restart: always
    volumes:
      - '${GITLAB_RUNNER_HOME}/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
